### ISSUE TITLE
训练的时候出错了

### ISSUE THREAD

**Issue by sovzzz** [innnky/so-vits-svc#109]
报错如下
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/so-vits-svc/train.py", line 108, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "/root/autodl-tmp/so-vits-svc/train.py", line 149, in train_and_evaluate
    y_hat_mel = mel_spectrogram_torch(
  File "/root/autodl-tmp/so-vits-svc/mel_processing.py", line 104, in mel_spectrogram_torch
    spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device],
  File "/root/miniconda3/lib/python3.8/site-packages/torch/functional.py", line 632, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by devNegative-asm** [comment]
make sure the cuda version used by torch is the same as the cuda drivers you have installed
