### ISSUE TITLE
训练出现错误 RuntimeError: cuFFT only supports dimensions whose sizes are powers of two when computing in half precision, but got a signal size of[1280]

### ISSUE THREAD

**Issue by pymastera** [innnky/so-vits-svc#11]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/featurize/so-vits-svc/train.py", line 109, in run
    [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/home/featurize/so-vits-svc/train.py", line 157, in train_and_evaluate
    hps.data.mel_fmax
  File "/home/featurize/so-vits-svc/mel_processing.py", line 105, in mel_spectrogram_torch
    center=center, pad_mode='reflect', normalized=False, onesided=True, return_complex=False)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/functional.py", line 573, in stft
    normalized, onesided, return_complex)
RuntimeError: cuFFT only supports dimensions whose sizes are powers of two when computing in half precision, but got a signal size of[1280]

环境
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

torch 1.10和1.13.1均出现此错误

**Comment by innnky** [comment]
啊有可能是前几天我把fp16设为默认了，没想到会报错，那我还是改回去

**Comment by innnky** [comment]
把config里fp16_run 设为false
