### ISSUE TITLE
colab非初次训练时报错

### ISSUE THREAD

**Issue by bilbillm** [innnky/so-vits-svc#130]
第二次训练，上次训练到D_2000和G_2000
运行 查看显卡 克隆GitHub仓库 安装依赖 下载必要模型文件 加载谷歌网盘 操作后
选择将训练后的模型保存到谷歌云盘 不使用预模型
开始训练时报错
`The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
Reusing TensorBoard on port 6006 (pid 1166), started 0:06:35 ago. (Use '!kill 1166' to kill it.)
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    main()
  File "train.py", line 42, in main
    hps = utils.get_hparams()
  File "/content/so-vits-svc/utils.py", line 263, in get_hparams
    config = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by TomoGaSukunai** [comment]
训练需要的素材可以参考 一键脚本里的 ```数据集预处理```下 ```已经预处理过数据集的话，就可以跳过预处理部分 直接从云盘解压处理过的数据 以及配置文件``` 段落
包括```configs/config.json``` ```filelists/train.txt``` ```filelists/val.txt``` 以及对应 ```/content/so-vits-svc/dataset```文件夹下的文件
之前训练时 备份过数据集的话 执行 ```已经预处理过数据集的话，就可以跳过预处理部分 直接从云盘解压处理过的数据 以及配置文件```  再带上模型文件就行
