### ISSUE TITLE
python preprocess_hubert_f0.py  报错

### ISSUE THREAD

**Issue by leeseean** [innnky/so-vits-svc#134]
```D:\AI cover\so-vits-svc-main\so-vits-svc-main>python preprocess_hubert_f0.py
Traceback (most recent call last):
  File "D:\AI cover\so-vits-svc-main\so-vits-svc-main\preprocess_hubert_f0.py", line 8, in <module>
    from pyworld import pyworld
  File "C:\Users\Administrator\anaconda3\lib\site-packages\pyworld\__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld\pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by innnky** [comment]
pip install pyworld==0.2.5 numpy==1.20.3 试试

**Comment by JunityZhan** [comment]
Please try pip install --upgrade pyworld. I encountered same issue and fixed

**Comment by linfen0** [comment]
> 

it works in autodl !

**Comment by linfen0** [comment]
在autodl下 pip install pyworld==0.2.5 numpy==1.20.3 后 就正常了

**Comment by TheTarr** [comment]
> 

打扰了老大，还是报错
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 88, got 96
