### ISSUE TITLE
制作翻唱时报错却没有错误原因 AssertionError when i use inference_main.py

### ISSUE THREAD

**Issue by vegetablekchicken** [innnky/so-vits-svc#151]
制作翻唱时提示这个 我吧目标歌曲调到一秒也不行 应该不是显存的原因
it still AssertionError when I shorten clean_names to 1 second
F:\music\so-vits-svc-32k>python ./inference_main.py
DEBUG:matplotlib.pyplot:Loaded backend agg version v2.2.
Traceback (most recent call last):
  File "F:\music\so-vits-svc-32k\inference_main.py", line 19, in <module>
    svc_model = Svc(model_path, config_path)
  File "F:\music\so-vits-svc-32k\inference\infer_tool.py", line 166, in __init__
    self.load_model()
  File "F:\music\so-vits-svc-32k\inference\infer_tool.py", line 184, in load_model
    _ = utils.load_checkpoint(self.net_g_path, self.net_g_ms, None)
  File "F:\music\so-vits-svc-32k\utils.py", line 89, in load_checkpoint
    assert os.path.isfile(checkpoint_path)
AssertionError

**Comment by Misaka17032** [comment]
```python
assert os.path.isfile(checkpoint_path)
```
根据报错，程序在尝试载入checkpoint时文件读写遇到了问题。可能是因为没有指定模型路径或者路径错误的原因，请尝试检查checkpoint_path的值。

**Comment by vegetablekchicken** [comment]
> 
啊是的 我模型名填错了，我竟然在这个问题上卡了好几天，太感谢了
