### ISSUE TITLE
推理时RuntimeError，模型大小不匹配

### ISSUE THREAD

**Issue by Yan233th** [innnky/so-vits-svc#179]
请问这个模型大小不匹配该怎么调整啊，它报了一堆INFO:root: XXX is not in the checkpoint，然后是
Traceback (most recent call last):
  File "D:\114514\Program Files\so-vits-svc\inference_main.py", line 19, in <module>
    svc_model = Svc(model_path, config_path)
  File "D:\114514\Program Files\so-vits-svc\inference\infer_tool.py", line 166, in __init__
    self.load_model()
  File "D:\114514\Program Files\so-vits-svc\inference\infer_tool.py", line 184, in load_model
    _ = utils.load_checkpoint(self.net_g_path, self.net_g_ms, None)
  File "D:\114514\Program Files\so-vits-svc\utils.py", line 114, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "C:\ProgramData\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for dec.noise_convs.0.weight: copying a param with shape torch.Size([256, 1, 128]) from checkpoint, the shape in current model is torch.Size([256, 1, 64]).
        size mismatch for dec.noise_convs.1.weight: copying a param with shape torch.Size([128, 1, 16]) from checkpoint, the shape in current model is torch.Size([128, 1, 8]).
        size mismatch for dec.noise_convs.2.weight: copying a param with shape torch.Size([64, 1, 8]) from checkpoint, the shape in current model is torch.Size([64, 1, 4]).
        size mismatch for dec.noise_convs.3.weight: copying a param with shape torch.Size([32, 1, 4]) from checkpoint, the shape in current model is torch.Size([32, 1, 1]).
        size mismatch for dec.conv_post.weight_v: copying a param with shape torch.Size([1, 16, 7]) from checkpoint, the shape in current model is torch.Size([1, 32, 7]).

**Comment by NaruseMioShirakana** [comment]
你载入的是G模型还是D模型
