### ISSUE TITLE
训练都正常，推理一直OOM。请问有没有方法降低推理的显存占用？

### ISSUE THREAD

**Issue by MistEO** [innnky/so-vits-svc#26]
## 环境

软件 Windows 11，`conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 -c pytorch -c conda-forge`

硬件 3090 24G, 32G RAM

## 训练时的瞎折腾

- 训练的 backend 我自己改成了 gloo （因为 win 不支持 nccl，会报错，不知道有没有影响？）
- batch size 手动改 config 调到了 24 （自动生成的是 12），lr 调到了 0.0002（自动生成的是 0.0001）

## 报错输出

```log
(vits) PS E:\Code\so-vits-svc> python .\inference_main.py
DEBUG:matplotlib.pyplot:Loaded backend agg version v2.2.
INFO:root:Loaded checkpoint 'logs/32k/G_9000.pth' (iteration 9001)
#=====segment start, 6.7s======
hubert use time:2.4384868144989014
vits use time:0.308591365814209
#=====segment start, 209.5s======
hubert use time:0.06551909446716309
Traceback (most recent call last):
  File ".\inference_main.py", line 54, in <module>
    out_audio, out_sr = svc_model.infer(spk, tran, raw_path)
  File "E:\Code\so-vits-svc\inference\infer_tool.py", line 224, in infer
    audio = self.net_g_ms.infer(x_tst, f0=f0, g=sid)[0,0].data.float()
  File "E:\Code\so-vits-svc\models.py", line 346, in infer
    z_p, m_p, logs_p, c_mask = self.enc_p_(c, c_lengths, f0=f0_to_coarse(f0))
  File "E:\ENV\anaconda\envs\vits\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Code\so-vits-svc\models.py", line 119, in forward
    x = self.enc_(x * x_mask, x_mask)
  File "E:\ENV\anaconda\envs\vits\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Code\so-vits-svc\attentions.py", line 39, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "E:\ENV\anaconda\envs\vits\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Code\so-vits-svc\attentions.py", line 143, in forward
    x, self.attn = self.attention(q, k, v, mask=attn_mask)
  File "E:\Code\so-vits-svc\attentions.py", line 160, in attention
    scores_local = self._relative_position_to_absolute_position(rel_logits)
  File "E:\Code\so-vits-svc\attentions.py", line 225, in _relative_position_to_absolute_position
    x_flat = F.pad(x_flat, commons.convert_pad_shape([[0,0],[0,0],[0,length-1]]))
  File "E:\ENV\anaconda\envs\vits\lib\site-packages\torch\nn\functional.py", line 4174, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 6.54 GiB (GPU 0; 24.00 GiB total capacity; 18.85 GiB already allocated; 365.36 MiB free; 20.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## 问题描述

开了个 gpu-z 看了下是真的吃满了显存然后炸了，想问下正常来说推理就是会吃这么多显存吗？我放的待转换 wav 大概 50M。

如果就是要吃这么多显存，有没有什么方法哪怕推理的慢一点但是可以降低显存占用让能正常跑完的？（比如把待转换音频切片？）
如果正常不吃这么多，可能的问题在哪里呢？

先谢谢大佬_(:з」∠)_

**Comment by MistEO** [comment]
咨询了一下认识的大佬，原来推理也是要切片的。第一次玩音频相关，不是太懂。切片之后已经 ok 了，打扰了。再次感谢大佬的项目！
