### ISSUE TITLE
onnx_export.py Error

### ISSUE THREAD

**Issue by X-T-E-R** [innnky/so-vits-svc#27]
I have installed the newest onnx and onnxruntime or something.
While running onnx_export.py
```
Traceback (most recent call last):
  File "onnx_export.py", line 74, in <module>
    main(False,True)
  File "onnx_export.py", line 54, in main
    torch.onnx.export(SVCVITS,
  File "C:\Users\xxoy1\anaconda3\envs\sovits\lib\site-packages\torch\onnx\utils.py", line 504, in export
    _export(
  File "C:\Users\xxoy1\anaconda3\envs\sovits\lib\site-packages\torch\onnx\utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\xxoy1\anaconda3\envs\sovits\lib\site-packages\torch\onnx\utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\xxoy1\anaconda3\envs\sovits\lib\site-packages\torch\onnx\utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\xxoy1\anaconda3\envs\sovits\lib\site-packages\torch\onnx\utils.py", line 1909, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::diff' to ONNX opset version 16 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
```

and in the py file, it is

```
        SVCVITS.eval()
        torch.onnx.export(SVCVITS,
                        (
                            test_hidden_unit.to(device),
                            test_lengths.to(device),
                            test_pitch.to(device),
                            test_sid.to(device)
                        ),
                        f"checkpoints/{path}/model.onnx",
                        dynamic_axes={
                            "hidden_unit": [0, 1],
                            "pitch": [1]
                        },
                        do_constant_folding=False,
                        opset_version=16,
                        verbose=False,
                        input_names=input_names,
                        output_names=output_names)
```

I have tried to downgrade onnx to 1.7 or 1.12, but in vain

**Comment by X-T-E-R** [comment]
哦，回答的话中文就可以了（我以为要用英文的来着）

**Comment by NaruseMioShirakana** [comment]
请克隆整个仓库，该仓库内部不仅仅只更改了外面的两个文件，内部的文件均有改动。
这个报错就是Onnx不支持的算子引起的。
至于为什么单独分出来两个onnx相关的文件，是因为这两个文件不能在原版基础上改动，改了会影响训练，所以单独分出来了，其他不会影响正常训练的东西都在原版的基础上修改了。
