### ISSUE TITLE
训练报错IndexError: list index out of range

### ISSUE THREAD

**Issue by RincolF** [innnky/so-vits-svc#39]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
  File "G:\so-vits-svc-32k\train.py", line 108, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "G:\so-vits-svc-32k\train.py", line 130, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\so-vits-svc-32k\data_utils.py", line 87, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "G:\so-vits-svc-32k\data_utils.py", line 57, in get_audio
    spk = filename.split(os.sep)[-2]
IndexError: list index out of range

不知道是不是因为显存只有4G的原因。。

**Comment by RincolF** [comment]
把config里的batch_size改成2之后

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\RincolF\AppData\Local\Programs\Python\Python39\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
  File "G:\so-vits-svc-32k\train.py", line 108, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "G:\so-vits-svc-32k\train.py", line 130, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 9948, 22340, 21140, 7660, 22552, 616, 12860) exited unexpectedly

**Comment by innnky** [comment]
这是昨天更新出的一个问题，，主要是windows和linux使用的分隔符'/'和'\'引起的问题，我更新了一下代码，你看看能不能行了

**Comment by RincolF** [comment]
> 这是昨天更新出的一个问题，，主要是windows和linux使用的分隔符'/'和''引起的问题，我更新了一下代码，你看看能不能行了

更新之后之前的解决了，就是显存还是太小了，batch_size默认12报了错。
RuntimeError: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 0; 4.00 GiB total capacity; 1.96 GiB already allocated; 0 bytes free; 1.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

把batch_size从12改成1到6，会有RuntimeError: DataLoader worker (pid(s)这样的问题

**Comment by innnky** [comment]
你试试把所有spec.pt文件删除，或者干脆dataset全删了重新执行一遍数据集预处理过程

**Comment by innnky** [comment]
是在不行你回滚到这个版本看看，https://github.com/innnky/so-vits-svc/tree/178ad58e9dafceed7f4bf469010c64b2b240fefb
