### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by RincolF** [innnky/so-vits-svc#42]
在colab上训练后在本地推理报了错

DEBUG:matplotlib.pyplot:Loaded backend agg version v2.2.
INFO:root:Loaded checkpoint 'logs/32k/G_2000.pth' (iteration 286)
C:\Users\RincolF\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
Traceback (most recent call last):
  File "G:\SVS\inference_main.py", line 37, in <module>
    audio_data, audio_sr = slicer.chunks2audio(wav_path, chunks)
  File "G:\SVS\inference\slicer.py", line 133, in chunks2audio
    audio, sr = torchaudio.load(audio_path)
  File "C:\Users\RincolF\AppData\Roaming\Python\Python39\site-packages\torchaudio\backend\soundfile_backend.py", line 196, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "C:\Users\RincolF\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\RincolF\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\Users\RincolF\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'raw\\ハレハレヤ.wav': File contains data in an unknown format.

**Comment by RincolF** [comment]
将soundfile从0.10.3.post1改成0.11.0之后没有报错，但是并不执行

G:\SVS>python inference_main.py
DEBUG:matplotlib.pyplot:Loaded backend agg version v2.2.
INFO:root:Loaded checkpoint 'logs/32k/G_2000.pth' (iteration 286)

G:\SVS>

**Comment by RincolF** [comment]
已解决。
_采自psychopy：I suspect that the wav file in question is compressed, which isn’t supported by the pygame library you use: (https://stackoverflow.com/questions/47640886/pygame-will-only-play-some-wav-files)
You could convert the file to an uncompressed wav. Then, it should work._
soundfile依旧是0.11.0，问题出在我是将曲子手动重命名从mp3改成wav，之后用格式工厂转了一下就可以了
