### ISSUE TITLE
执行训练命令后报错 [inline_container.cc] PytorchStreamWriter failed writing file data/271: file write failed 和 unexpected pos 190007680 vs 190007572

### ISSUE THREAD

**Issue by Astro-Lee** [innnky/so-vits-svc#46]
当我执行训练命令后`python train.py -c configs/config.json -m 32k`

这里是模型训练时的正常输出.

接下来是报错部分:
```bash
INFO:32k:Saving model and optimizer state at iteration 55 to ./logs\32k\G_5000.pth
INFO:32k:Saving model and optimizer state at iteration 55 to ./logs\32k\D_5000.pth
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main()
  File "train.py", line 48, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "D:\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "D:\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 423, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 650, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:450] . PytorchStreamWriter failed writing file data/271: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\Administrator\Desktop\so-vits-svc-32k\train.py", line 108, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "C:\Users\Administrator\Desktop\so-vits-svc-32k\train.py", line 223, in train_and_evaluate
    utils.save_checkpoint(net_d, optim_d, hps.train.learning_rate, epoch,
  File "C:\Users\Administrator\Desktop\so-vits-svc-32k\utils.py", line 127, in save_checkpoint
    torch.save({'model': state_dict,
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 424, in save
    return
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 290, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:325] . unexpected pos 190007680 vs 190007572
```
谢谢~

**Comment by innnky** [comment]
我的推测，你硬盘满了，存不下了

**Comment by Astro-Lee** [comment]
的确是硬盘满了, 谢谢你的解答!
