### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by nyancatda** [innnky/so-vits-svc#49]
```
python preprocess_hubert_f0.py

Traceback (most recent call last):
  File "so-vits-svc\preprocess_hubert_f0.py", line 8, in <module>
    from pyworld import pyworld
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\pyworld\__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld\pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
```
pip show numpy
Name: numpy
Version: 1.19.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD
Location: c:\users\xxxx\appdata\local\programs\python\python39\lib\site-packages
Requires:
Required-by: basicsr, easyocr, facexlib, filterpy, gfpgan, imageio, librosa, matplotlib, numba, opencv-python, opencv-python-headless, PyWavelets, pyworld, resampy, scikit-image, scikit-learn, scipy, shapely, tb-nightly, tifffile, torchvision
```

我已经尝试按照requirements.txt将Numpy 版本安装为1.19.2，但是依然出现这个错误

**Comment by SuCicada** [comment]
你好 我遇到了一样的问题，请问你是怎么解决的呢

**Comment by nyancatda** [comment]
> 你好 我遇到了一样的问题，请问你是怎么解决的呢

按照requirements.txt里面的版本一个个按照过去，全部替换为指定版本

**Comment by SuCicada** [comment]
明白了，非常感谢
