### ISSUE TITLE
Error happened at the first step "No module named '_cffi_backend'"

### ISSUE THREAD

**Issue by JstzjgscSergino** [innnky/so-vits-svc#58]
Hi. I was trying to run your script but an error happened at the first step with "python resample.py":

> ModuleNotFoundError: No module named '_cffi_backend'

So I used "pip install cffi" but it said:

> Requirement already satisfied: cffi in e:\python3\lib\site-packages (1.15.1)
> Requirement already satisfied: pycparser in e:\python3\lib\site-packages (from cffi) (2.21)

Then I typed "pip install cryptography" and it said:

> Collecting cryptography
>   Downloading cryptography-39.0.1-cp36-abi3-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 19.6 MB/s eta 0:00:00
> Requirement already satisfied: cffi>=1.12 in e:\python3\lib\site-packages (from cryptography) (1.15.1)
> Requirement already satisfied: pycparser in e:\python3\lib\site-packages (from cffi>=1.12->cryptography) (2.21)
> Installing collected packages: cryptography
> Successfully installed cryptography-39.0.1

Then I ran "python -c "import _cffi_backend"" and it still gave me:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named '_cffi_backend'

Please, can anyone help? My Python ver is 3.9.0.

Thank you very much!

<br>
<hr>
<br>

以下几行是由谷歌翻译器翻译的，因此可能有些混乱。

你好。 我试图运行您的脚本，但在第一步“python resample.py”时发生错误：

> ModuleNotFoundError: No module named '_cffi_backend'

所以我使用了“pip install cffi”，但它说：

> Requirement already satisfied: cffi in e:\python3\lib\site-packages (1.15.1)
> Requirement already satisfied: pycparser in e:\python3\lib\site-packages (from cffi) (2.21)

然后我输入“pip install cryptography”，它说：

> Collecting cryptography
>   Downloading cryptography-39.0.1-cp36-abi3-win_amd64.whl (2.5 MB)
>      ---------------------------------------- 2.5/2.5 MB 19.6 MB/s eta 0:00:00
> Requirement already satisfied: cffi>=1.12 in e:\python3\lib\site-packages (from cryptography) (1.15.1)
> Requirement already satisfied: pycparser in e:\python3\lib\site-packages (from cffi>=1.12->cryptography) (2.21)
> Installing collected packages: cryptography
> Successfully installed cryptography-39.0.1

然后我运行了“python -c”import _cffi_backend“”，它仍然给我：

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named '_cffi_backend'

请问，有人可以帮忙吗？ 我的 Python 版本是 3.9.0。

非常感谢！

**Comment by t-naeem** [comment]
Try uninstalling and installing it again:
pip uninstall cffi
pip install cffi
