### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 29: invalid start byte

### ISSUE THREAD

**Issue by dfmjndm** [innnky/so-vits-svc#64]
训练模型时出现如下报错
INFO:32k:{'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 17920, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 384, 'port': '8001'}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 1280, 'hop_length': 320, 'win_length': 1280, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 2}, 'spk': {'qingxu': 0}, 'model_dir': './logs\\32k'}
WARNING:32k:G:\AI 阿梓\Azi_singer is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main()
  File "train.py", line 48, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "G:\AI 阿梓\Azi_singer\env38\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "G:\AI 阿梓\Azi_singer\env38\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "G:\AI 阿梓\Azi_singer\env38\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "G:\AI 阿梓\Azi_singer\env38\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\AI 阿梓\Azi_singer\train.py", line 64, in run
    train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps)
  File "G:\AI 阿梓\Azi_singer\data_utils.py", line 26, in __init__
    self.audiopaths = load_filepaths_and_text(audiopaths)
  File "G:\AI 阿梓\Azi_singer\utils.py", line 219, in load_filepaths_and_text
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "G:\AI 阿梓\Azi_singer\utils.py", line 219, in <listcomp>
    filepaths_and_text = [line.strip().split(split) for line in f]
  File "G:\AI 阿梓\Azi_singer\env38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 29: invalid start byte

请按任意键继续. . .

**Comment by cpuopt** [comment]
文件名有日语，预处理的时候就会变乱码
