### ISSUE TITLE
页面文件太小，无法完成操作

### ISSUE THREAD

**Issue by dfmjndm** [innnky/so-vits-svc#67]
PS G:\AI azi\Azi_singer> env38\python.exe train.py -c configs/config.json -m 32k     
INFO:32k:{'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 
12, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 17920, 'init_lr_ratio': 
1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 384, 
'port': '8001'}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 1280, 'hop_length': 320, 'win_length': 1280, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 
3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 2}, 'spk': {'qingxu': 
0}, 'model_dir': './logs\\32k'}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
./logs\32k\G_0.pth
INFO:32k:emb_g.weight is not in the checkpoint
INFO:32k:Loaded checkpoint './logs\32k\G_0.pth' (iteration 1)
./logs\32k\D_0.pth
INFO:32k:Loaded checkpoint './logs\32k\D_0.pth' (iteration 1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\AI azi\Azi_singer\env38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "G:\AI azi\Azi_singer\env38\lib\multiprocessing\spawn.py", line 125, in _main 
    prepare(preparation_data)
  File "G:\AI azi\Azi_singer\env38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "G:\AI azi\Azi_singer\env38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "G:\AI azi\Azi_singer\env38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "G:\AI azi\Azi_singer\env38\lib\runpy.py", line 97, in _run_module_code       
    _run_code(code, mod_globals, init_globals,
  File "G:\AI azi\Azi_singer\env38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\AI azi\Azi_singer\train.py", line 8, in <module>
    import torch
  File "G:\AI azi\Azi_singer\env38\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "G:\AI azi\Azi_singer\env38\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by dfmjndm** [comment]
参考下文解决   https://blog.csdn.net/weixin_46133643/article/details/125042903
