### ISSUE TITLE
训练开始时torch.multiprocessing.spawn.ProcessRaisedException出现错误，报RuntimeError

### ISSUE THREAD

**Issue by NyankoSong** [innnky/so-vits-svc#74]
你好！

我在尝试执行`python train.py -c configs/config.json -m 32k`时，终端正常输出了配置情况后，出现了`torch.multiprocessing.spawn.ProcessRaisedException`错误，具体输出信息如下：
```python
INFO:32k:{'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 12, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 17920, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 384, 'port': '8001'}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 1280, 'hop_length': 320, 'win_length': 1280, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 2}, 'spk': {'speaker0': 0}, 'model_dir': './logs/32k'}
Traceback (most recent call last):
  File "D:\FolderName\so-vits-svc\train.py", line 281, in <module>
    main()
  File "D:\FolderName\so-vits-svc\train.py", line 48, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps))
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 188, in start_processes
    while not context.join():
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
  File "D:\FolderName\so-vits-svc\train.py", line 60, in run
    dist.init_process_group(backend='nccl', init_method='env://', world_size=n_gpus, rank=rank)
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\distributed\distributed_c10d.py", line 576, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\distributed\rendezvous.py", line 229, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\distributed\rendezvous.py", line 157, in _create_c10d_store
    return TCPStore(
RuntimeError
```

作为可能需要的信息：由于文件路径字符串中出现"/"和"\\"混用的情况，我对代码增加了把"\\"替换为"/"的步骤。

百度无果，但提示可能与GPU调用有关，这里给出显卡的信息（实际用的是cu113）：
```PowerShell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.02       Driver Version: 528.02       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P8     5W /  70W |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

想请问该如何解决？谢谢！

**Comment by S-Typedef** [comment]
Hi, I have a same problem with you. Above the output of yours, there are some tcp error informations. I notied an error "WinError 10013" which means tcp cannt bind to the port defined in ${PROJECT_HOME}/configs/config.json:23. Generally, It means port is already in use, or maybe without permission. It works when I chang it to another number.

**Comment by NyankoSong** [comment]
> Hi, I have a same problem with you. Above the output of yours, there are some tcp error informations. I notied an error "WinError 10013" which means tcp cannt bind to the port defined in ${PROJECT_HOME}/configs/config.json:23. Generally, It means port is already in use, or maybe without permission. It works when I chang it to another number.

感谢回复！

但我已经没有办法确认是否是端口被占用的问题导致的程序异常中断了。我把整个虚拟环境删掉并重新搭建了数次，现在似乎勉强能工作了。

**Comment by S-Typedef** [comment]
Good luck!
