### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by laiyoi** [innnky/so-vits-svc#96]
PS E:\so-vits-svc> E:\python\python3.8.10\python.exe .\train.py -c .\configs\config.json -m 32k
INFO:32k:{'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 2, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 17920, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 384, 'port': '8001'}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 1280, 'hop_length': 320, 'win_length': 1280, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 6}, 'spk': {'astolfo': 0, 'liuchan': 1, 'xiaobangguo': 2}, 'model_dir': './logs\\32k'}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
./logs\32k\G_0.pth
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
E:\python\python3.8.10\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File ".\train.py", line 281, in <module>
    main()
  File ".\train.py", line 48, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "E:\python\python3.8.10\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "E:\python\python3.8.10\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "E:\python\python3.8.10\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "E:\python\python3.8.10\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\so-vits-svc\train.py", line 108, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "E:\so-vits-svc\train.py", line 187, in train_and_evaluate
    scaler.step(optim_g)
  File "E:\python\python3.8.10\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 313, in step
    return optimizer.step(*args, **kwargs)
  File "E:\python\python3.8.10\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "E:\python\python3.8.10\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "E:\python\python3.8.10\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\python\python3.8.10\lib\site-packages\torch\optim\adamw.py", line 162, in step
    adamw(params_with_grad,
  File "E:\python\python3.8.10\lib\site-packages\torch\optim\adamw.py", line 219, in adamw
    func(params,
  File "E:\python\python3.8.10\lib\site-packages\torch\optim\adamw.py", line 273, in _single_tensor_adamw
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (4) must match the size of tensor b (6) at non-singleton dimension 0

**Comment by youyuanyi** [comment]
应该是你的wav文件名字原因，尝试在每个文件名前面加个英文字母,不要用纯数字命名。
It should be the name of your wav file. Try adding an English letter to the front of each file name, rather than using pure numbers
