### ISSUE TITLE
Exception: No pretrained model found. when trying to train.

### ISSUE THREAD

**Issue by jurassicjordan** [innnky/so-vits-svc#97]
I've got the hubert model, what other models Am i missing for the purposes of training?

```
Traceback (most recent call last):
  File "/home/jordancruz/Tools/so-vits-svc/train.py", line 284, in <module>
    main()
  File "/home/jordancruz/Tools/so-vits-svc/train.py", line 49, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/jordancruz/anaconda3/envs/so_svc2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jordancruz/anaconda3/envs/so_svc2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/jordancruz/anaconda3/envs/so_svc2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jordancruz/Tools/so-vits-svc/train.py", line 93, in run
    _, _, _, epoch_str = utils.load_checkpoint(utils.latest_checkpoint_path(hps.model_dir, "G_*.pth"), net_g,
  File "/home/jordancruz/Tools/so-vits-svc/utils.py", line 169, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jordancruz/anaconda3/envs/so_svc2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/jordancruz/Tools/so-vits-svc/train.py", line 99, in run
    raise Exception("No pretrained model found.")
Exception: No pretrained model found.

```

**Comment by jurassicjordan** [comment]
my mistake, I missed the part in the documentation about the pretrained models
