### ISSUE TITLE
求助：在3.生成hubert与f0 报错 SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by ANINwindows** [innnky/so-vits-svc#99]
![image](https://user-images.githubusercontent.com/44198387/219944355-74a1702e-3ab4-4853-a8a0-db3ba996fe6b.png)
我尝试了换CUDA版本，11.7、11.8、12.0
重新安装numpy  1.20.3、1.23、1.24.2
在硬盘创建虚拟内存（之前人脸合成的时候有个问题是因为这个）
真的没办法啦，有没有大佬指点下
(base) PS F:\so-vits-svc-32k> python preprocess_hubert_f0.py
Traceback (most recent call last):
  File "F:\so-vits-svc-32k\preprocess_hubert_f0.py", line 12, in <module>
    import utils
  File "F:\so-vits-svc-32k\utils.py", line 10, in <module>
    import librosa
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\ProgramData\Anaconda3\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

**Comment by linfen0** [comment]
不知道你的虚拟环境有没有安装依赖
